[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
#> cargo build --release --target x86_64-unknown-linux-musl

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
#> cargo build --release --target=x86_64-pc-windows-msvc